import React from 'react';
import { FileText, Download, Calendar, User } from 'lucide-react';
import type { Report } from '../../types';

interface ReportTableProps {
  reports: Report[];
  onDownload: (report: Report) => void;
  onDelete: (reportId: string) => void;
}

const ReportTable: React.FC<ReportTableProps> = ({ reports, onDownload, onDelete }) => (
  <div className="bg-white rounded-lg border border-gray-200">
    <div className="p-4 border-b border-gray-200 flex items-center justify-between">
      <h3 className="text-lg font-semibold text-gray-900">Generated Reports</h3>
      <div className="flex gap-2">
        <input
          type="text"
          placeholder="Search reports..."
          className="px-3 py-1 border border-gray-300 rounded text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <select className="px-3 py-1 border border-gray-300 rounded text-sm focus:outline-none focus:ring-2 focus:ring-blue-500">
          <option>All Types</option>
          <option>Asset Utilization</option>
          <option>Assignment History</option>
          <option>Repair Analytics</option>
          <option>Vendor Performance</option>
        </select>
      </div>
    </div>
    
    <div className="overflow-x-auto">
      <table className="w-full">
        <thead className="bg-gray-50">
          <tr>
            <th className="text-left p-4 text-sm font-medium text-gray-900">REPORT NAME</th>
            <th className="text-left p-4 text-sm font-medium text-gray-900">TYPE</th>
            <th className="text-left p-4 text-sm font-medium text-gray-900">GENERATED BY</th>
            <th className="text-left p-4 text-sm font-medium text-gray-900">DATE</th>
            <th className="text-left p-4 text-sm font-medium text-gray-900">STATUS</th>
            <th className="text-left p-4 text-sm font-medium text-gray-900">SIZE</th>
            <th className="text-left p-4 text-sm font-medium text-gray-900">ACTIONS</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-200">
          {reports.map((report) => (
            <tr key={report.id} className="hover:bg-gray-50">
              <td className="p-4">
                <div className="flex items-center gap-3">
                  <FileText className="w-8 h-8 text-blue-500" />
                  <div>
                    <p className="font-medium text-gray-900">{report.name}</p>
                    <p className="text-sm text-gray-500">{report.description}</p>
                  </div>
                </div>
              </td>
              <td className="p-4">
                <span className="px-2 py-1 text-xs font-medium bg-blue-100 text-blue-800 rounded-full">
                  {report.type}
                </span>
              </td>
              <td className="p-4">
                <div className="flex items-center gap-2">
                  <User className="w-4 h-4 text-gray-400" />
                  <span className="text-sm text-gray-900">{report.generatedBy}</span>
                </div>
              </td>
              <td className="p-4">
                <div className="flex items-center gap-2">
                  <Calendar className="w-4 h-4 text-gray-400" />
                  <span className="text-sm text-gray-900">{report.dateGenerated}</span>
                </div>
              </td>
              <td className="p-4">
                <span className={`px-2 py-1 text-xs font-medium rounded-full ${
                  report.status === 'Generated' 
                    ? 'bg-green-100 text-green-800'
                    : report.status === 'Generating'
                    ? 'bg-orange-100 text-orange-800'
                    : 'bg-red-100 text-red-800'
                }`}>
                  {report.status}
                </span>
              </td>
              <td className="p-4 text-sm text-gray-900">{report.fileSize || '-'}</td>
              <td className="p-4">
                <div className="flex gap-2">
                  {report.status === 'Generated' && (
                    <button 
                      onClick={() => onDownload(report)}
                      className="text-blue-600 hover:text-blue-800 text-sm flex items-center gap-1"
                    >
                      <Download className="w-3 h-3" />
                      Download
                    </button>
                  )}
                  <button 
                    onClick={() => onDelete(report.id)}
                    className="text-red-600 hover:text-red-800 text-sm"
                  >
                    Delete
                  </button>
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  </div>
);

export default ReportTable;